# Stage 1: Build
FROM node:20-alpine AS builder
WORKDIR /app

RUN corepack enable && corepack prepare yarn@3.6.1 --activate

# Copy Yarn config files before installing dependencies
COPY package.json yarn.lock ./
COPY .yarn .yarn
COPY .yarnrc.yml ./

RUN yarn install --immutable

# Copy the rest of your project
COPY . .

RUN yarn build

# Stage 2: Production
FROM node:20-alpine AS runner
WORKDIR /app

RUN corepack enable && corepack prepare yarn@3.6.1 --activate

COPY --from=builder /app/package.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/.yarn ./.yarn
COPY --from=builder /app/.yarnrc.yml ./.yarnrc.yml

# Install production dependencies
RUN yarn install

EXPOSE 3000

CMD ["yarn", "start"]
